### PR TITLE
change z-index for list

### LINKED ISSUE #2070: Bug: MapBox logo appears in wrong place (over the text results)
#### Describe the bug 

Severity 1/5 (where 5 is worst)

The MapBox logo is appearing off the map and in the wrong place on Desktop in Safari on Mac :)

#### Additional details / screenshot

Screenshot 2024-03-28 at 2 29 40 PM

#### Device configuration
- Device: Mac
- OS version: Sonoma
- Browser: Safari

### LINKED ISSUE #2084: Postion Mapbox attribution behind result list
### Overview
mapbox attribution logo is above results list. We want it to be behind the list. 
image

### Action Items
set z-index for list higer

### PR DESCRIPTION
**Pull request by junjun107**
closes #2084 
closes #2070 

Before Mapbox logo shows above list.
image
After logo stays behind list
image

### CODE REVIEW

**Review by qiqicodes — COMMENTED** [review]
~~Why change the z-index for the list? Changed value behaves the same as the original value.~~

File: client/src/components/FoodSeeker/SearchResults/layouts/Desktop.js [hunk 1]
```diff
@@ -87,7 +87,7 @@ const DesktopLayout = ({ filters, list, map }) => {
             left: isListPanelOpen ? 0 : "-524px",
             top: "120px",
             height: "100%",
-            zIndex: "1",
+            zIndex: "3",
```
Comment (qiqicodes) [inline client/src/components/FoodSeeker/SearchResults/layouts/Desktop.js:90]: Keep as numeric value, only use string defaults such as `tooltip` or `modal` for preset arbitrary number.

File: client/src/components/FoodSeeker/SearchResults/layouts/Desktop.js [hunk 2]
```diff
@@ -87,7 +87,7 @@ const DesktopLayout = ({ filters, list, map }) => {
...
             background: "white",
           }}
         >
```
Comment (qiqicodes) [inline client/src/components/FoodSeeker/SearchResults/layouts/Desktop.js:93]: remove z index from the button on line 116. The shadow comes from the svg file.

**Review by qiqicodes — CHANGES_REQUESTED** [review]
Removing line 22-58 from `DrawerLeftArrowButton.js` should address issue #2080

**Comment by junjun107** [comment]
> Why change the z-index for the list? Changed value behaves the same as the original value.

Not sure what you mean. Change z-index for list keeps mapbox logo behind the list. That is the desired result.

File: client/src/components/FoodSeeker/SearchResults/layouts/Desktop.js (hunk 2 above)
Comment (junjun107) [reply client/src/components/FoodSeeker/SearchResults/layouts/Desktop.js:93]: This ticket is for mapbox logo's z-index. I think you are mistaken #2084 with #2080

Comment (qiqicodes) [reply client/src/components/FoodSeeker/SearchResults/layouts/Desktop.js:93]: Nit: For consistency and best practice, if a z-index value of 3 achieves the desired effect, it's recommended to use the numeric value (3) instead of the string ('3').

Comment (qiqicodes) [reply client/src/components/FoodSeeker/SearchResults/layouts/Desktop.js:93]: Considering this pull request addresses issue #2084, I'll proceed with opening a new pull request for issue #2080. Please ignore my previous suggestion about removing lines from the `DrawerLeftArrowButton.js` file.

Comment (junjun107) [reply client/src/components/FoodSeeker/SearchResults/layouts/Desktop.js:90]: fixed

**Review by qiqicodes — APPROVED** [review]
