### PR TITLE
Organization Edit Errors and Confirmation Warnings #2556

### LINKED ISSUE #2556: Dev: Add warnings to Organization Edit Form when Submission / Approval requirements aren't yet met
### Overview
We need to add warning content to the Organization form, so that when you are validating or approving a validation, that you know why you can't approve it, or submit it.

### Action Items

- [x] Red badges on each tab show the number of fields that either fail validation or are required to submit or approve.
- [x] Red border that highlight around the fields that need validation, including a border around confirmation check boxes that need to be checked in order to submit or approve a listing.
- [x] Summary box of all validation or submission/approval  errors on all pages, regardless of the active tab.

#### Details
<details><summary>Warning contents to Organization Form Mock Up</summary>

Image

</details> 

### Additional Information
<details><summary>An animated gif of Invalid confirmation checkbox on the Identification page in Organization form</summary>

Image

</details> 

- Unchecked confirmation box keeps users from approving and the tooltip is not helpful.
- Sophie suggested error message: "[Address] must be confirmed before approval". (The error message should specify which confirmation is missing (e.g. phone, email, business hours).

<details><summary>Screenshot of invalid link error on Contact Details Page in Organization form</summary>

Image

</details> 

- When social media link is invalid, as shown above, there is an error message on the "contact details" page. However, if on a different tab and trying to click "approve", the button remains blue and doesn't approve. There is no warning message. It would be helpful if there was an error message on/next to the "approve button". For example, "Instagram link is invalid".

### PR DESCRIPTION
**Pull request by whitneywind**
- Resolves #2556 
 - Adds a validation error summary box and red badge counts on tabs. These show validation errors that prevent saving and fields that need confirmation in order to submit
 - Required fields that are missing or add to the error count and info box immediately. Confirmation warnings and accompanying checkbox red borders appear when the user attempts to submit for review

screenshot

### CODE REVIEW

**Comment by whitneywind** [comment]
screencapture-localhost-3000-admin-organizationedit-5082-2026-03-24-09_29_09

**Comment by whitneywind** [comment]
More changes after feedback from Bonnie:
screencapture-localhost-3000-admin-organizationedit-5082-2026-03-24-15_42_03

File: client/src/components/Admin/OrganizationEdit.jsx [hunk 1]
```diff
@@ -563,16 +664,42 @@ const OrganizationEdit = (props) => {
...
+                                }}
+                              >
+                                <span style={{ paddingRight: 10 }}>{label}</span>
+                              </Badge>
+                            ) : (
+                              label
+                            )
+                          }
+                          {...a11yProps(index)}
+                        />
```
Comment (hanapotski) [inline client/src/components/Admin/OrganizationEdit.jsx:1007]: nice refactor 🥳

File: client/src/components/Admin/OrganizationEdit.jsx [hunk 2]
```diff
@@ -662,303 +798,410 @@ const OrganizationEdit = (props) => {
...
+                                  )}
+                                </ul>
+                              </Box>
+                            )}
+                          </Box>
+                        </Box>
+                      )}
+                  </Stack>
+                  <Stack direction="row" justifyContent="flex-end" spacing={2}>
+                    {user && (user.isAdmin || user.isCoordinator) ? (
```
Comment (hanapotski) [inline client/src/components/Admin/OrganizationEdit.jsx]: can we move this to a helper function so it's easier to follow? something like

```
renderActionButton() {
  if (this) {
    return this
  } 
...
  return default
}
```

Comment (whitneywind) [reply client/src/components/Admin/OrganizationEdit.jsx]: @hanapotski Yes! How does it look now?

File: client/src/components/Admin/OrganizationEdit.jsx [hunk 3]
```diff
@@ -418,6 +502,308 @@ const OrganizationEdit = (props) => {
...
+                setFieldValue(
+                  "verificationStatusId",
+                  VERIFICATION_STATUS.NEEDS_VERIFICATION
+                );
+                setNextUrl("/admin/verificationadmin");
+                handleSubmit();
+              }}
+              disabled={
+                isSubmitting ||
+                values.verifivation_status_id ===
```
Comment (SAUMILDHANKAR) [inline client/src/components/Admin/OrganizationEdit.jsx]: tiny typo, let me test if this is trivial

File: client/src/components/Admin/OrganizationEdit.jsx [hunk 4]
```diff
@@ -502,6 +502,308 @@ const OrganizationEdit = (props) => {
     }));
   };
 
+  const renderActionButtons = ({ values, errors, isSubmitting, setFieldValue, handleSubmit }) => {
+    if (user?.isAdmin || user?.isCoordinator) {
```
Comment (SAUMILDHANKAR) [inline client/src/components/Admin/OrganizationEdit.jsx:506]: Image
I was not seeing the buttons so Gemini AI suggested to add a ```return (``` after this line

File: client/src/components/Admin/OrganizationEdit.jsx [hunk 5]
```diff
@@ -502,6 +502,308 @@ const OrganizationEdit = (props) => {
...
+                  },
+                });
+              }}
+              disabled={!user.isAdmin || !values.id}
+            >
+              Delete
+            </Button>
+          </div>
+        </Tooltip>
+      </Stack>
```
Comment (SAUMILDHANKAR) [inline client/src/components/Admin/OrganizationEdit.jsx]: ```);```
return closing parenthesis here.

File: client/src/components/Admin/OrganizationEdit.jsx (hunk 4 above)
Comment (whitneywind) [reply client/src/components/Admin/OrganizationEdit.jsx:506]: Good catch! Thank you

**Review by hanapotski — APPROVED** [review]
