### PR TITLE
Fix filter panel warnings

### LINKED ISSUE #2021: Investigate MUI Out-Of-Range Console Warnings
### Overview
When running locally, we are getting several MUI warnings that make it difficult to trouble shoot any other errors or warnings from the console.

The warnings are:
- MUI: You have provided an out-of-range value `false` for the select (name="day") component. Consider providing a value that matches one of the available options or ''. The available values are `SUN`, `MON`, `TUE`, `WED`, `THU`, `FRI`, `SAT` 
- MUI: You have provided an out-of-range value `false` for the select (name="time") component. Consider providing a value that matches one of the available options or ''. The available values are `12:00AM`, `01:00AM`, `02:00AM`, `03:00AM`, `04:00AM`, `05:00AM`, `06:00AM`, `07:00AM`, `08:00AM`, `09:00AM`, `10:00AM`, `11:00AM`, `12:00PM`, `01:00PM`, `02:00PM`, `03:00PM`, `04:00PM`, `05:00PM`, `06:00PM`, `07:00PM`, `08:00PM`, `09:00PM`, `10:00PM`, `11:00PM`
- etc.

### Action Items
- [ ] Investigate how to fix this issue
- [ ] Make changes

### PR DESCRIPTION
**Pull request by hanapotski**
Fixes #2021

### CODE REVIEW

File: client/src/components/FoodSeeker/SearchResults/ResultsFilters/FilterPanel.js [hunk 1]
```diff
@@ -175,50 +176,52 @@ export default function FilterPanel({ mealPantry }) {
...
+                    key={`${key}-select`}
+                    name={key}
+                    value={openTime[key]}
+                    onChange={(e) => handleOpenTimeChange(e)}
+                    displayEmpty
+                    renderValue={(selected) => {
+                      if (openTime.radio !== "Customized" || !selected) {
+                        return <em>{OPEN_TIME_DROPDOWNS[key].placeholder}</em>;
+                      }
+                      return undefined;
```
Comment (qiqicodes) [inline client/src/components/FoodSeeker/SearchResults/ResultsFilters/FilterPanel.js:208]: need the original logic, or the placeholder will not display any value after day and time are selected.
```
return openTime.radio !== "Customized" ||
  selected.length === 0 ? (
  <em>{OPEN_TIME_DROPDOWNS[key].placeholder}</em>
) : (
  selected
);
```
Current branch behavior:

https://github.com/hackforla/food-oasis/assets/68657634/67ff2c7e-e874-40b5-bd7c-3c6017c9cbfb

**Review by qiqicodes — CHANGES_REQUESTED** [review]

**Review by qiqicodes — APPROVED** [review]
lgtm
