### PR TITLE
Vertical centering on mobile #2219

### LINKED ISSUE #2219: Serious Bug: Map - Mobile map pans incorrectly when viewing an organization
VERY HIGH PRIORITY -- HOT FIX REQUESTED.

### Progress

- [x] Create partial-solution to get it mostly working again #2229
- [x] Push hot fix to public
- [x] Create solution where map pans to new location **without** resetting zoom level (please assign @fancyham and @Shienny1 to PR to review)
- [x] Push to public

(~Sept 15, 2024)
Re-creating this as a new issue per @hanapotski because the solution for 
- #2028 
didn't seem to work -- the issue with the map panning to the wrong location still exists.

A hint for this: Part of the issue seems to be the map's zoom level.  At default zoom, it's not a problem.  Changing the zoom causes the problem.

#### Describe the bug 

Serious bug:

When viewing a list of organizations, and tapping one to get details about it, the map does not update show or highlight the organization’s pin.  Often the pin is way off-screen.

The map should re-center (ideally with a smooth scroll/pan) on the highlighted pin automatically, ideally showing both the user’s current location and the pin so that they can determine the relative location.

#### Steps to reproduce the issue

(if applicable, please specify platform (iOS, Android, Windows, Mac version) and brower)

1. Go to foodoasis.net
2. Enter a location to get a list of organizations
3. Scroll around the map, **zoom in or zoom out**
4. Tap an organization to view the organization detail page
5. Map does not update to show the organization’s pin.

See more videos at
-#2028

#### What's the expected result?

Map should re-center on the organization’s pin automatically, each time a new organization is viewed.  

Ideally, the map smoothly pans to the new location, and ideally, the user’s current location / entered address is also visible on the map (though this may be difficult if the user has panned the map manually)

See Apple or Google maps or Yelp on mobile phones for example.

#### What's the actual result?

The organization’s pin may be highlighted, but is often off-screen with no indication for how to find the pin itself.

This is a regression — the previous version centered on highlighted pins properly.

#### Additional details / screenshot

A similar problem appears when searching from the map screen. 
1. From landing page, enter an address. On desktop, map Pin appears in the wrong place but map pans correct place at first.
IMG_1253

2. Do a search again from the map page and the map now re-centers in the wrong place, and the pin doesn’t move to the correct place. 
IMG_1252

https://github.com/user-attachments/assets/4ee431c6-d986-4282-9694-7ef13badf7d1

To it might have something to do with loading the page for the first time vs going to a new location

#### Device configuration
- Device: iPhone 13 mini
- OS version: 17.4
- Browser: Safari

### Related issues

- #2168 
- #2028 

### When making your PR
Please assign @fancyham and @Shienny1 to PRs so we can review

### PR DESCRIPTION
**Pull request by whitneywind**
Fixes #2219 

- This PR updates the useMapbox hook to set the mobile vertical(latitude) offset dynamically according to screen height.

### CODE REVIEW

File: client/src/hooks/useMapbox.js [hunk 1]
```diff
@@ -35,13 +35,21 @@ export const useMapbox = () => {
...
-    const latitudeOffset =
-      baseLatOffset * Math.pow(2, 11 - currentZoom) * screenHeightFactor;
+
+    function calculateLatOffset(screenHeight) {
+      const baseHeight = 550;
+      const rate = 0.006 / 50; // approximately 0.006 deg per 50 pixels
+      return 0.034 + (screenHeight - baseHeight) * rate;
+    }
+
+    const heightOffsetFactor = !screenHeight
```
Comment (hanapotski) [inline client/src/hooks/useMapbox.js:48]: this looks good 🙌 just curious why we had to check for this? would there be a case where `window.innerHeight` wouldn't exist? 🤔

Comment (whitneywind) [reply client/src/hooks/useMapbox.js:48]: That's a good question! In most cases, it should be accessible, so the check isn't strictly necessary. I was just being extra cautious for some rare edge cases, like maybe in an unusual initial load where it returns 0. But for our usage, it's probably safe to assume it’s there!
